### ISSUE TITLE
Create Registration Form UI

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#16]
#### **Objective**
Design and implement a user-friendly registration form using HTML and CSS.

---

#### **Requirements**
1. **Form Fields**:
   - Full Name (Text input)
   - Email (Text input)
   - Password (Password input)
   - Confirm Password (Password input)

2. **Design**:
   - Use a clean and simple design.
   - Add labels and placeholders for all fields.
   - Ensure responsiveness for both desktop and mobile devices.

3. **Additional Features**:
   - Include a submit button.
   - Add basic styling (CSS) for proper alignment and spacing.

---

#### **Deliverables**
- A fully functional registration form designed in HTML and styled with CSS.

#### **Acceptance Criteria**
- The form displays all required fields.
- The design is clean and responsive.

**Assignee:** [Insert Name]  
**Labels:** `frontend` `UI`

**Comment by ImashiRodrigo** [comment]
fb2fc79b260e247993bb391f1af74ed0945b456b - The registration form is completed from following commit.

**Comment by ImashiRodrigo** [comment]
c9f91b051cd32ec378e9efb0bdabd88c19dac2be - Client side Validation Completed.

**Comment by ImashiRodrigo** [comment]
42cff2dd8dd228c411549fcd51c0e8c06cb8fa40 - The registration form is completed from the following commit.

**Comment by dmkwelivitage** [comment]
@ImashiRodrigo 

The issue will remain closed as it meets the basic functionality requirements. However, there is room for improvement in the CSS styling.

### Suggestions for Improvement:

1. **Color Scheme**:
   - Ensure the color scheme used is a bit more polished.
   - Use complementary colors for buttons, links, and other interactive elements.

Feel free to reopen the issue if you encounter any challenges while improving the styles or require further clarification.
