### ISSUE TITLE
Password Hashing

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#19]
#### **Objective**
Securely hash user passwords before storing them in the database.

---

#### **Requirements**
1. Use `password_hash` in PHP to hash the password.
2. Use `password_verify` during login to validate the password.

---

#### **Deliverables**
- PHP code for hashing and verifying passwords.

#### **Acceptance Criteria**
- Passwords are hashed before being stored.
- Login functionality verifies the hashed passwords correctly.

**Assignee:** [Insert Name]  
**Labels:** `backend` `security`

**Comment by ImashiRodrigo** [comment]
6efb8120b04f6ce40a175c40372b3899ebf8c459 - Password hashing completed. @dmkwelivitage
