### ISSUE TITLE
Database Migration Script

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#20]
#### **Objective**
Create a database migration script to set up the `users` table.

---

#### **Requirements**
1. Fields for the `users` table:
   - `id` (Primary Key, Auto Increment)
   - `full_name` (VARCHAR, 255)
   - `email` (VARCHAR, 255, UNIQUE)
   - `password` (VARCHAR, 255)
   - `created_at` (TIMESTAMP)

2. Write a script to create the table in MySQL.

---

#### **Deliverables**
- A SQL script to create the `users` table.

#### **Acceptance Criteria**
- The `users` table is created with the specified fields.

**Assignee:** [Insert Name]  
**Labels:** `database` `migration`

**Comment by ImashiRodrigo** [comment]
330e6b85e9a74789ab215feebb3b8c665a03ea63 - Added database script @dmkwelivitage
