### ISSUE TITLE
Check Email Uniqueness

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#21]
#### **Objective**
Ensure that no duplicate email addresses are allowed in the database.

---

#### **Requirements**
1. Query the database to check if the email already exists.
2. Display an error message if the email is already in use.

---

#### **Deliverables**
- PHP code to check email uniqueness during registration.

#### **Acceptance Criteria**
- Duplicate email addresses are not allowed.
- Appropriate error messages are displayed.

**Assignee:** [Insert Name]  
**Labels:** `backend` `validation`

**Comment by ImashiRodrigo** [comment]
6efb8120b04f6ce40a175c40372b3899ebf8c459 - Check email uniqueness was completed @dmkwelivitage
