### ISSUE TITLE
Form Submission and Error Handling

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#22]
#### **Objective**
Handle form submission and display appropriate error or success messages.

---

#### **Requirements**
1. Process form data after validation.
2. Display success messages on successful registration.
3. Display error messages for failed validations or database issues.

---

#### **Deliverables**
- PHP code to handle form submission and error reporting.

#### **Acceptance Criteria**
- Form submission works as intended.
- Error and success messages are displayed correctly.

**Assignee:** [Insert Name]  
**Labels:** `backend` `error-handling`

**Comment by ImashiRodrigo** [comment]
6efb8120b04f6ce40a175c40372b3899ebf8c459 - Form submission and error handling was completed from following @dmkwelivitage
