### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#23]
#### **Objective**
Ensure that the registration process is secure and free of vulnerabilities.

---

#### **Requirements**
1. Use prepared statements to prevent SQL injection.
2. Sanitize and validate all user inputs.
3. Use HTTPS for secure communication.

---

#### **Deliverables**
- PHP code that implements secure practices.

#### **Acceptance Criteria**
- The system is secure and adheres to best practices.

**Assignee:** [Insert Name]  
**Labels:** `security` `backend`

**Comment by ImashiRodrigo** [comment]
6efb8120b04f6ce40a175c40372b3899ebf8c459 - Security  Checking was completed. @dmkwelivitage
