### ISSUE TITLE
Create Login Form UI

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#24]
#### **Objective**
Design a simple and user-friendly login form using HTML and CSS.

---

#### **Requirements**
1. **Form Fields**:
   - Email (Text input)
   - Password (Password input)

2. **Design**:
   - Clean and intuitive layout.
   - Add labels and placeholders for clarity.
   - Include a "Login" button.

3. **Additional Features**:
   - Add a "Forgot Password" link (optional).

---

#### **Deliverables**
- A fully functional login form designed in HTML and styled with CSS.

#### **Acceptance Criteria**
- The form is visually appealing and responsive.
- The layout works across different devices.

**Assignee:** [Insert Name]  
**Labels:** `frontend` `UI`

**Comment by UmedhyaIndeewari** [comment]
The errors in this issue are fixed through this code-e9fd466cb1011243c871330ea4a2e80c2756fd93

**Comment by dmkwelivitage** [comment]
Will not reopen the issue minor fixes are needed in order for it to be completed. Make sure to complete and reference the commit ID in this thread
