### ISSUE TITLE
Authenticate User Credentials

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#27]
#### **Objective**
Verify user credentials securely using the `users` table.

---

#### **Requirements**
1. Fetch user data by email.
2. Use `password_verify` to match the password.
3. Return appropriate responses for success or failure.

---

#### **Deliverables**
- PHP code for credential authentication.

#### **Acceptance Criteria**
- Authentication works as expected.
- Invalid credentials return error messages.

**Assignee:** [Insert Name]  
**Labels:** `backend` `authentication`

**Comment by UmedhyaIndeewari** [comment]
Added the passwords including the hashing part. Pls check and let me know  whether there is any changes to be done 8f00cee6cbfadd2067540ed08e955433048c73a8  @dmkwelivitage
