### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#30]
#### **Objective**
Display meaningful error messages for login failures.

---

#### **Requirements**
1. Handle:
   - Invalid email format.
   - Missing password.
   - Incorrect credentials.

2. Display user-friendly error messages.

---

#### **Deliverables**
- PHP and front-end code for error display.

#### **Acceptance Criteria**
- Errors are clear and actionable.
- User experience is seamless.

**Assignee:** [Insert Name]  
**Labels:** `frontend` `error-handling`

**Comment by UmedhyaIndeewari** [comment]
Error handling techniques are done.Pls check me and give me the feedback 8f00cee6cbfadd2067540ed08e955433048c73a8 @dmkwelivitage
