### ISSUE TITLE
Rate-Limiting

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#31]
#### **Objective**
Prevent brute force attacks by implementing rate-limiting.

---

#### **Requirements**
1. Track failed login attempts by IP or user.
2. Lock accounts temporarily after 5 failed attempts.
3. Display a lockout message.

---

#### **Deliverables**
- PHP code for rate-limiting logic.

#### **Acceptance Criteria**
- Brute force attacks are mitigated.
- Locked accounts reset after a set period.

**Assignee:** [Insert Name]  
**Labels:** `backend` `security`

**Comment by UmedhyaIndeewari** [comment]
not needed

**Comment by UmedhyaIndeewari** [comment]
not done
