### ISSUE TITLE
Design Profile Page

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#33]
#### **Objective**
Create a user-friendly profile page to display user information.

---

#### **Requirements**
1. Display the following user details:
   - Full Name
   - Email
   - Profile Picture (if available)
2. Include an "Edit Profile" button.
3. Ensure the page is responsive and visually appealing.

---

#### **Deliverables**
- HTML/CSS for the profile page.

#### **Acceptance Criteria**
- Profile page displays all required user details.
- Page is responsive and works across devices.

**Assignee:** [Insert Name]  
**Labels:** `frontend` `UI`

**Comment by InushK** [comment]
profile page designed

**Comment by InushK** [comment]
profile page is designed,
Create the database,
update profile page for the database connection
c7be4a88c822b9e5dc17c8613abd727f124d4453

**Comment by InushK** [comment]
profile page is designed,
Create the database,
update profile page for the database connection
c7be4a88c822b9e5dc17c8613abd727f124d4453

**Comment by dmkwelivitage** [comment]
@InushK 

Before closing the issue, please double-check your code thoroughly. It appears that the CSS for the update profile page has not been completed. Here are a few points to keep in mind:

### Key Notes:
1. **Folder Naming Conventions**:
   - Avoid using spaces in folder names.
   - Use lowercase letters and separate words with dashes (e.g., `update-profile` instead of `Update Profile`).

2. **File Naming Conventions**:
   - Follow the same practice as above—use dashes instead of spaces for file names.

3. **Database Connection**:
   - Consider using PDO (PHP Data Objects) for establishing database connections. This is optional but recommended for better security and flexibility.
```php

<?php
// Database configuration
$host = 'localhost'; // Replace with your database host
$dbname = 'your_database_name'; // Replace with your database name
$username = 'your_username'; // Replace with your database username
$password = 'your_password'; // Replace with your database password

try {
    // Establishing the PDO connection
    $dsn = "mysql:host=$host;dbname=$dbname;charset=utf8mb4";
    $pdo = new PDO($dsn, $username, $password);

    // Setting PDO attributes for better error handling
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);

    echo "Database connection established successfully.";
} catch (PDOException $e) {
    // Handling connection errors
    echo "Error: Unable to connect to the database. " . $e->getMessage();
}
?>

```

4. **User Interface (UI)**:
   - The UI could benefit from enhancements. Aim for a more polished and consistent design across the page.

### Action Items:
- Ensure the CSS for the update profile page is fully implemented and aligned with the rest of the application design.
- Review the folder and file naming conventions to maintain consistency.
- If opting for PDO, refactor the code accordingly and test the connection.
- Apply necessary UI improvements to enhance the user experience.

Once the above points are addressed, proceed with closing the issue. Let me know if you require further assistance or clarification.

**Comment by InushK** [comment]
errors are fixed
