### ISSUE TITLE
Develop Profile Edit Form

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#34]
#### **Objective**
Implement a form to allow users to edit their profile details.

---

#### **Requirements**
1. Include fields for:
   - Full Name
   - Email
   - Profile Picture (optional)
2. Provide a "Save" button for updates and a "Cancel" button to revert changes.

---

#### **Deliverables**
- HTML/CSS for the edit form.

#### **Acceptance Criteria**
- The edit form is functional and matches the design.
- The "Cancel" button reverts changes.

**Assignee:** [Insert Name]  
**Labels:** `frontend` `UI`

**Comment by thakshila-dilrukshi** [comment]
Develop Profile Edit Form functionality is done
In the profile_edit.php line 85 to 118
