### ISSUE TITLE
Profile Picture Upload

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#37]
#### **Objective**
Enable users to upload and update their profile pictures.

---

#### **Requirements**
1. Allow users to select an image file.
2. Validate the file type and size.
3. Store the image securely on the server and save its path in the database.

---

#### **Deliverables**
- PHP code for handling file uploads.
- Database updates to store image paths.

#### **Acceptance Criteria**
- Users can upload a profile picture.
- Uploaded files meet the validation criteria.

**Assignee:** [Insert Name]  
**Labels:** `backend` `file-upload`

**Comment by thakshila-dilrukshi** [comment]
Profile Picture Upload
In the profile-edit.php line 51 to 83
