### ISSUE TITLE
Database Update Functionality

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#38]
#### **Objective**
Update user details in the `users` table.

---

#### **Requirements**
1. Use prepared statements to update:
   - Full Name
   - Email
   - Profile Picture (if updated)
2. Ensure email uniqueness before saving.

---

#### **Deliverables**
- PHP code for database updates.

#### **Acceptance Criteria**
- User details are updated successfully.
- Unique email constraint is enforced.

**Assignee:** [Insert Name]  
**Labels:** `backend` `database`

**Comment by InushK** [comment]
In the profile-edit.php line 30 to 49 are the functions for the database update
