### ISSUE TITLE
Session Security

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#39]
#### **Objective**
Ensure only authorized users can edit their profiles.

---

#### **Requirements**
1. Check the user's session before displaying or editing the profile.
2. Redirect unauthorized users to the login page.

---

#### **Deliverables**
- PHP code for session validation.

#### **Acceptance Criteria**
- Only logged-in users can access profile management.
- Unauthorized access is handled securely.

**Assignee:** [Insert Name]  
**Labels:** `backend` `security`

**Comment by thakshila-dilrukshi** [comment]
Session Security functionality is done
In the profile-edit.php line 2 to 18 
Temporarily remove session security as login is not implemented yet
