### ISSUE TITLE
Feedback and Confirmation Messages

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#40]
#### **Objective**
Provide clear feedback for profile updates or errors.

---

#### **Requirements**
1. Show a confirmation message for successful updates.
2. Display error messages for validation or database issues.

---

#### **Deliverables**
- UI code for feedback messages.

#### **Acceptance Criteria**
- Feedback is clear and consistent.
- Users are informed of success or errors.

**Assignee:** [Insert Name]  
**Labels:** `frontend` `UI`

**Comment by InushK** [comment]
in the profile,php and profile-edit.php code files are implemented for the Feedback and Confirmation Messages here are some examples,
profile-edit.php
line 149
                if (!emailPattern.test(email)) {
                    document.getElementById('emailError').textContent = 'Please enter a valid email address.';
                    isValid = false;
                }

line 107
        if ($stmt) {
            $stmt->bind_param("sssi", $fullName, $email, $profilePicturePath, $userId);
            if ($stmt->execute()) {
                $successMessage = "Profile updated successfully!";
            } else {
                $errorMessage = "Error: Could not update the profile.";
            }
            $stmt->close();
        }
