### ISSUE TITLE
Develop Reusable Footer

### ISSUE THREAD

**Issue by dmkwelivitage** [Ulysium-MetaEngine/practice-icbt-team#44]
#### **Objective**
Create a footer component with useful links and information.

---

#### **Requirements**
1. Include:
   - Links for "Contact Us," "Privacy Policy," and "Terms of Service."
   - A copyright notice (e.g., "© 2024 Your App Name").
2. Ensure the footer is consistent across all pages.
3. Use CSS for styling.

---

#### **Deliverables**
- HTML and CSS for the footer.

#### **Acceptance Criteria**
- The footer is responsive and functional.
- Links work as expected.

**Assignee:** [Insert Name]  
**Labels:** `frontend` `HTML` `CSS`

**Comment by MCNJayamuthu** [comment]
@dmkwelivitage the following issues is closed with the commit number cf3a598c1e793d0668eea6f388d762131f14a9a3
